[versions]

leaf-loader = "1.6.0"
leaf-loom = "0.7.1"
zomboid = "42.19.0-unstable+1aa820d"

[libraries]

leaf-loader = { module = "dev.aoqia.leaf:loader", version.ref = "leaf-loader" }
zomboid = { module = "com.theindiestone:zomboid", version.ref = "zomboid" }

[plugins]

leaf-loom = { id = "dev.aoqia.leaf.loom", version.ref = "leaf-loom" }
